export { default as getAgeByIDCard } from './getAgeByIDCard'
export { default as getBirthdayByIDCard } from './getBirthdayByIDCard'
export { type VitePlatform, default as getEnvData } from './getEnvData'
export { default as getGenderByIDCard } from './getGenderByIDCard'
export { default as getIsDev } from './getIsDev'
export { default as getStyleBackgroundImage } from './getStyleBackgroundImage'
